# Based on Quarkus' Dockerfile.jvm template for Gradle
FROM registry.access.redhat.com/ubi9/openjdk-25:1.24

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/

USER root
RUN mkdir -p /work/data \
    && chown -R 185:root /work

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

VOLUME ["/work/data"]

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]