FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7
WORKDIR /work/
RUN chown 1001 /work \
    && mkdir /work/data \
    && chmod -R "g+rwX" /work \
    && chown -R 1001:root /work
COPY --chown=1001:root --chmod=0755 build/*-runner /work/application

EXPOSE 8080
USER 1001

VOLUME ["/work/data"]

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]