[versions]
spring-boot = "2.6.6"
tomcat = "9.0.60"
jacoco = "0.8.7"
spotless = "6.4.1"

[libraries]
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version = "1.70" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
