[versions]
spring-boot = "2.6.7"
tomcat = "9.0.62"
jacoco = "0.8.8"
spotless = "6.5.1"

[libraries]
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version = "1.70" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
