CREATE TABLE IF NOT EXISTS TSP_REQUEST(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HASH_ALGORITHM VARCHAR(50) NOT NULL,
    HASH VARCHAR(200) NOT NULL,
    NONCE VARCHAR(200),
    CERTIFICATE_REQUESTED BOOLEAN,
    TSA_POLICY_ID VARCHAR(50),
    ASN_ENCODED VARCHAR(3000) NOT NULL
);

CREATE TABLE IF NOT EXISTS TSP_RESPONSE(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL,
    STATUS_STRING VARCHAR(200),
    FAILURE_INFO INT,
    GENERATION_TIME TIMESTAMP WITH TIME ZONE,
    SERIAL_NUMBER VARCHAR (200),
    REQUEST_ID BIGINT NOT NULL,
    ASN_ENCODED VARCHAR(3000) NOT NULL,
    FOREIGN KEY(REQUEST_ID) REFERENCES TSP_REQUEST(ID)
);
