name: Check

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Gradle 'build' Task
        run: ./gradlew build

  check:
    name: "e2e tests ${{ matrix.type.name }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - name: jvm
            native: false
          - name: native
            native: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: execute e2e tests
        env:
          ORG_GRADLE_PROJECT_nativeImage: ${{ matrix.type.native }}
        run: ./gradlew testNative
